statnett/controller-runtime-viper

- .github/workflows/build.yml
This will allow the lint and test jobs to run in parallel, as recommended by [golangci-lint-action](https://github.com/golangci/golangci-lint-action#how-to-use).
> refactor(ci): split build workflow in lint/test jobs

- .github/workflows/release.yml
- .releaserc.yml
This is an initial attempt to create a release workflow. Proposing to run in dry run mode and with debug enabled until we know that we have something that might work.
Close #10
> ci: add initial release workflow

- .releaserc.yml
Fix initial syntax errors, ref. https://github.com/statnett/controller-runtime-viper/actions/runs/3633773271/jobs/6131166197
> fix(ci): correct syntax error in .releaserc.yml

- .golangci.yml
- pkg/zap/zap.go
This adds a couple of more linters disabled by default: https://golangci-lint.run/usage/linters/#disabled-by-default
> ci: add more golangci linters

- .releaserc.yml
It seems like the default preset handles our conventional commits correctly. I have tested this on my fork - which I should have done from the beginning.
> ci: make semantic-release work

- .github/dependabot.yml
Lets give Dependabot a try :-)
Close #3 
Inspired from: https://github.com/kubernetes-sigs/controller-runtime/blob/master/.github/dependabot.yml
> chore: enable dependabot for go and GH actions

- .github/workflows/build.yml
- .yamllint
This adds yamllint to our CI to ensure YAML-files are properly formatted.
> ci: add yamllint to CI

- .github/workflows/lint-pr.yml
This adds a GitHub workflow that comments on the PR when the title is not in according to the conventional commits standard.
Due to permission rules in GitHub, this workflow must run with `pull_request_target` (context of the PR target branch) which means it is not run on this PR. After merging this, we should verify that it works by creating another PR.
This will replace the Semantic PR GitHub App, and I will disable it after merge.
> ci: add convential commits PR lint workflow

- .releaserc.yml
This PR unsets the `dryRun`  property in `.releaserc.yml`, and with the "feat:" prefix in the PR title, this should trigger our first auto-release. Hopefully, the new version will be `0.1.0`. 😉
> feat: enable automatic releases

- .github/workflows/release.yml
I hope replacing the default GITHIB_TOKEN with a fine-grained personal access token (PAT) will fix the release issue of creating protected tags. Example: https://github.com/statnett/controller-runtime-viper/actions/runs/3715017150/jobs/6299673134
> ci: replace GITHUB_TOKEN with PAT

- .github/workflows/release.yml
I have a feeling we need to use the PAT added in https://github.com/statnett/controller-runtime-viper/pull/31 to checkout in the release workflow.
Closes #32 (I hope)
> ci: use PAT to perform checkout in release workflow

- .github/dependabot.yml
- .github/workflows/release.yml
- .releaserc.yml
By default, only fix/feat/BREAKING triggers a new semantic release. I think Go dependency updates also deserve a new release. This PR slightly modifies the Dependabot configuration so that Go dependency update PR should be prefixed with `build(deps):`. Then configures the semantic-release release configuration to trigger releases for those commits, and includes dependency updates in a separate section of the release notes.
Inspired by https://mattbun.io/posts/semantic-release-dependabot/, and tested in https://github.com/erikgb/test-ci-release.
> ci(release): make Dependabot dependency updates trigger patch releases

- .github/dependabot.yml
After modifying the Dependabot commit message, I notice that the PR title does not include scope. This will hopefully fix this.
> ci: make Dependabot include scope in PR title

- .github/workflows/ci.yml
To be able to add a build badge, and ensure that the build is passing on the default branch, this PR adds push to the default branch as a new CI workflow event.
> ci: run CI workflow on push to default branch

- .github/workflows/trivy.yml
This adds Trivy repository scanning as an addition to CodeQL: https://github.com/aquasecurity/trivy-action#using-trivy-to-scan-your-git-repo
Not sure if it actually works well with GitHub, since I don't see it here: https://github.com/statnett/controller-runtime-viper/security/code-scanning. But let's see after merge.
> ci: add workflow for Trivy repo scanning

- .github/workflows/prow-commands.yml
This is an introduction to https://github.com/jpmcb/prow-github-actions, which will allow us to use the most basic slash commands. We'll see how it works and eventually configure more features later.
> chore: introduce prow-github-actions

- README.md
It seems like GitHub badges can be pinned to branch: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-branch-parameter. This will ensure we show status for the correct branch workflow.
In addition, adding a query-param to the badge link, to make the list of workflows filtered by (default) branch.
> style: pin badges to default branch

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
This will allow workflows for subsequent commits to just keep the latest. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency for details.
> ci: cancel obsolete/redundant workflow automatically

- .github/workflows/lint-pr.yml
The PR linting is currently only checking the PR title, so I think it is sufficient to run the workflow on the PR `opened` and `edited` events.
> ci: no need to lint PR when code updated

- pkg/zap/zap.go
- pkg/zap/zap_test.go
This fixes a bug/TODO: the default encoder is dependant on dev-mode setting.
> fix: default encoder is dependent on dev-mode

- .github/workflows/release-please.yml
Trying to see if promoting the release-please workflow permissions [according to docs](https://github.com/google-github-actions/release-please-action/compare/d3c71f9a0a55385580de793de58da057b3560862...e0b9d1885d92e9a93d5ce8656de60e3b806e542c) can fix the release CI issues.
> ci: promote release-please workflow permissions

- .github/workflows/ci.yml
To get Go 1.20 support in golangci-lint, we need to bump to a recent version.
@mikaelol Are you able add a Renovate config for this? For future upgrades?
> chore: bump golangci-lint version

- .github/workflows/ci.yml
Fixes https://github.com/statnett/controller-runtime-viper/issues/156
> chore(renovate): maintain golangci-lint

- .github/workflows/release-please.yml
After resyncing the main branch in my fork, that triggered a workflow that will never work (in forks). GitHub has limited support for doing this, so the fix is a semi-hack inspired by https://github.com/orgs/community/discussions/26704.
> ci: don't run workflow requiring secrets in forks

- .github/workflows/release-please.yml
Same fix as https://github.com/statnett/image-scanner-operator/pull/506 for the same reasons.
> ci: allow users to trigger release-please workflow

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/lint-pr.yml
- .github/workflows/release-please.yml
- .github/workflows/scorecards.yml
We introduced step-security tools to see if they could provide some value to use. After almost a year, I don't see much value in them and suggest removing them.
> ci: remove all usage of step-security actions

- .github/semantic.yml
I think this is a leftover from our early GitHub days and can be deleted.
> chore: remove unused file

- .github/workflows/lint-pr.yml
- .github/workflows/release-please.yml
We have renamed the reusable GitHub workflow project and standardized on .yaml as file extensions. This updates what's needed to follow after.
> ci: fix broken links to reusable workflows

- .github/workflows/codeql.yaml
To fix:
As proposed, I don't think we need exact and reproducible action digests in this workflow.
> ci: fix codeql workflow

- .github/renovate.json5
Same config as proposed in https://github.com/statnett/image-scanner-operator/pull/638.
> ci: switch to Statnett default Renovate config and enable automerge

- go.mod
- go.sum
Kubernetes 1.29 requires Go 1.21, so I suggest doing this first.
> chore: bump to go 1.21

- go.mod
Required to upgrade K8s dependencies. It would be nice if Renovate could suggest PRs like this, but it seems like it insists on a full Go version requirement - which is very uncommon and something I would like to avoid.
> chore: upgrade Go mod requirements to Go 1.22

- go.mod
It seems like Renovate adds it, and I would prefer to avoid getting PRs for bumping the toolchain.
> chore: remove toolchain from go.mod

- pkg/zap/zap.go
This new goloangci-lint (gosec) error wasn't detected when upgrading golangci-lint. This resulted in all subsequent pipelines being borked. Hopefully, this minor change will fix the lint error.
> chore: make gosec linter happy

- .github/workflows/ci.yaml
- .golangci.yml
- pkg/zap/zap_test.go
It seems like the golangci-lint-action and golangci-lint must be upgraded to new major versions together.
The update also needs config migration and fixing a couple of new issues.
> chore: upgrade golangci-lint to new major versions
